name: SonarQube Code Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarQube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11

    - name: Cache SonarQube dependencies
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar

    - name: Run SonarQube Scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.organization=your_github_organization \
          -Dsonar.host.url=http://your-sonarqube-server-url \
          -Dsonar.login=$SONAR_TOKEN
